### PR TITLE
added quarterly strategic plan review/discussion

### PR DESCRIPTION
**Pull request by amyehodge**
updated based on strategic planning project with Kari and the goals for that project

### CODE REVIEW

**Comment by kariljordan** [comment]
Thanks @amyehodge for this PR. For context, Amy and I met today to review the year one strategic plan. I will complete the formatting changes this week, and this PR updates the timeline to include when progress toward the strategic plan will be communicated to the EC.

**Comment by lexnederbragt** [comment]
This is very good. I would like, however, to set up a yearly timepoint for establishing the next one-year plan. Would the October or November meeting be good for that?

**Comment by lexnederbragt** [comment]
Come to think of it, when would the EC establish its priorities for the year? Maybe the outgoing EC makes a suggestion at its last meeting, and the new EC approves it at its first?

**Comment by amyehodge** [comment]
@elliewix Your review and approval of this is still pending. I'd like to get this PR completed. Thanks.

**Comment by amyehodge** [comment]
@elliewix This PR has been sitting around since May. Could you review and approve it and then do the merge? Thanks.

**Review by elliewix — APPROVED** [review]

**Review by konrad — APPROVED** [review]

**Pull request merged**
