### PR TITLE
Added minutes Feb 2020

### PR DESCRIPTION
**Pull request by orchid00**
@carpentries/executive-council please approve Feb minutes

### CODE REVIEW

**Comment by kariljordan** [comment]
These look good to me.

**Review by amyehodge — APPROVED** [review]

**Review by Cedric-Chambers — APPROVED** [review]

**Comment by orchid00** [comment]
Can we merge? 
@lexnederbragt @elliewix @joslynnlee @zjsteyn @konrad ?

**Review by konrad — COMMENTED** [review]
Many thanks, @orchid00. I would change "EWilliams" to "E. Williams". Otherwise everything looks good.

**Comment by lexnederbragt** [comment]
Looks good to me. However, please have a look at the formatting of the bullet points, some are not rendered as such (especially for the first item).

**Review by lexnederbragt — APPROVED** [review]

**Review by konrad — APPROVED** [review]

**Review by elliewix — APPROVED** [review]

**Pull request merged**
