### PR TITLE
Transparency report until July 2021 and November 2021

### PR DESCRIPTION
**Pull request by malvikasharan**
This transparency report is from May-July 2021.

### CODE REVIEW

**Comment by kariljordan** [comment]
Thanks @malvikasharan!

**Comment by konrad** [comment]
Thanks for adding me as reviewer, @kariljordan. I think @masamiy as new Executive Council liaison in the Code of Conduct Committee is responsible now.

**Comment by orchid00** [comment]
@masamiy can we merge this?

**Comment by malvikasharan** [comment]
@masamiy I have updated the transparency report for the last quarter.

**Comment by malvikasharan** [comment]
Nudging for this to be reviewed.

**Comment by kariljordan** [comment]
@malvikasharan I sent Masami and email to nudge her.

**Comment by malvikasharan** [comment]
Thank you, Kari. We finished onboarding new members in the committee and would like to revisit these documents with them in the coming weeks. 🙏

**Comment by masamiy** [comment]
Hello, I am sorry for the delay. A report looks good!

**Pull request merged**
